apiVersion: v1
kind: Pod
metadata:
  name: k8s-msg-api
  labels:
    name: lbl-msg-api
spec:
  containers:
  - name: msg-api
    image: fra.ocir.io/fri5p1y9isrx/mysql_repo/mysql-sample-app:latest
    ports:
    - name: msg-api
      containerPort: 8080
  imagePullSecrets:
    - name: ocirsecret