apiVersion: v1
kind: Pod
metadata:
  name: k8s-msg-api
  labels:
    name: lbl-msg-api
spec:
  containers:
  - name: msg-api
    image: linoxide/msg-api:v0.0.1
    ports:
    - name: msg-api
      containerPort: 8080